// components/link-list.vue
<template>
  <div class="">
    <h2 class="menu-header text-center">Accounts</h2>
    <ul class="link-list-ul p-0">
      <li v-for="item in items" class="block w-full m-0">
        <a
          :href="item.href"
          class="fg-default"
          target="_blank"
          rel="noopener noreferrer"
        >
          <h3
            class="transition-colors bg-gray-400/10 hover:bg-gray-400/50 py-3 px-12"
          >
            {{ item.name }}
          </h3>
        </a>
      </li>
    </ul>
  </div>
</template>
<script>
export default {
  data() {
    return {
      items: [
        {
          // icon: github,
          name: "GitHub",
          href: "https://github.com/omemoji",
        },
        {
          // icon: twitter,
          name: "Twitter",
          href: "https://twitter.com/omemoji_art",
        },
        {
          // icon: instagram,
          name: "Instagram",
          href: "https://instagram.com/omemoji",
        },
        {
          // icon: zenn,
          name: "Zenn",
          href: "https://zenn.dev/omemoji/",
        },
        {
          name: "Keybase",
          href: "https://keybase.io/omemoji",
        },
      ],
    };
  },
};
</script>

// src/components/LinkList/index.tsx
import { FaGithub } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import { FaXTwitter } from "react-icons/fa6";
import { SiPixiv, SiZenn } from "react-icons/si";

type Props = {
  className?: string;
};

const iconClass = "ml-4";
const iconSize = "24px";

const linklist = [
  {
    icon: <FaGithub className={iconClass} size={iconSize} title="GitHub" />,
    href: "https://github.com/omemoji",
  },
  {
    icon: (
      <FaInstagram className={iconClass} size={iconSize} title="Instagram" />
    ),
    href: "https://instagram.com/omemoji",
  },
  {
    icon: (
      <FaXTwitter className={iconClass} size={iconSize} title="X (Twitter)" />
    ),
    href: "https://twitter.com/omemoji_art",
  },
  {
    icon: <SiZenn className={iconClass} size={iconSize} title="Zenn" />,
    href: "https://zenn.dev/omemoji",
  },
  {
    icon: <SiPixiv className={iconClass} size={iconSize} title="Pixiv" />,
    href: "https://www.pixiv.net/users/65949346",
  },
];

for (let i = 0; i < linklist.length; i++) {
  linklist[i].icon;
}

export default function LinkList({ className }: Props) {
  return (
    <div className={className + " " + "flex"}>
      {linklist.map((link) => (
        <div key={link.href}>
          <a className="w-8" href={link.href} target="_blank" rel="noopener">
            {link.icon}
          </a>
        </div>
      ))}
    </div>
  );
}
