// components/gallery.vue
<template>
  <div class="card card-shadow bg-white m-3 p-3">
    <h2 class="text-center mb-3">Gallery</h2>

    <div
      class="aspect-square overflow-y-auto over-contain card"
      style="font-size: 0"
    >
      <div
        v-for="(artwork, i) in artworks"
        :key="i"
        class="w-1/3 inline-block mb-0 border border-white"
      >
        <nuxt-link
          v-if="i <= 8"
          :to="'/Artworks/' + artwork.id"
          :title="artwork.title"
        >
          <nuxt-img
            :alt="artwork.title"
            :src="artwork.image"
            width="240"
            height="240"
            class="object-cover aspect-square w-full"
          />
        </nuxt-link>
        <nuxt-link
          v-if="i > 8"
          :to="'/Artworks/' + artwork.id"
          :title="artwork.title"
        >
          <nuxt-img
            :alt="artwork.title"
            :src="artwork.image"
            width="240"
            height="240"
            class="object-cover aspect-square w-full"
            loading="lazy"
          />
        </nuxt-link>
      </div>
    </div>
  </div>
</template>
<script>
import artworks from "@/assets/json/artworks.json";
export default {
  data() {
    return {
      artworks: artworks,
    };
  },
};
</script>

// src/components/Gallery.tsx
import { Picture } from "@/components/Image";
import type { Artwork } from "@/content/artworks";
import { imageUrl } from "@/features/image/assets";

/**
 * 作品一覧。正方形に切り抜いた 3 列のグリッド。
 *
 * 寸法は CSS（`aspect-ratio: 1` + `object-fit: cover`）が決めるため、
 * 本文の画像と違い width / height は出さない。AVIF のフォールバックは同じ経路を通す。
 */
export default function Gallery({ artworks }: { artworks: Artwork[] }) {
  return (
    <div className="gallery">
      {artworks.map((artwork) => {
        const src = imageUrl("artworks", artwork.id, artwork.src);

        return (
          <a key={artwork.id} href={`/artworks/${artwork.id}`}>
            <Picture src={src} alt={artwork.title} loading="lazy" decoding="async" />
          </a>
        );
      })}
    </div>
  );
}
