// components/gallery.vue
<template>
  <div class="card card-shadow bg-white m-3 p-3">
    <h2 class="text-center mb-3">Gallery</h2>

    <div
      class="aspect-square overflow-y-auto over-contain card"
      style="font-size: 0"
    >
      <div
        v-for="(artwork, i) in artworks"
        :key="i"
        class="w-1/3 inline-block mb-0 border border-white"
      >
        <nuxt-link :to="'/Artworks/' + artwork.id" :title="artwork.title">
          <nuxt-img
            :alt="artwork.title"
            :src="artwork.image"
            provider="ipx_fixed"
            width="240"
            height="240"
            quality="25"
            class="object-cover aspect-square w-full"
            loading="lazy"
          />
        </nuxt-link>
      </div>
    </div>
  </div>
</template>
<script>
import artworks from "@/assets/json/artworks.json";
export default {
  data() {
    return {
      artworks: artworks,
    };
  },
};
</script>

// src/components/Gallery/index.tsx
import { artData } from "lib/data";
import Link from "next/link";
import Image from "next/image";

type Props = {
  className?: string;
  artworks: Array<artData>;
};

export default async function Gallery({ className, artworks }: Props) {
  return (
    <>
      <div className={className + " " + "gallery block"}>
        {artworks.map((artwork) => (
          <div key={artwork.slug} className="w-1/3 inline-block">
            <Link href={"/artworks/" + artwork.slug}>
              <Image
                className="m-0 aspect-square object-cover"
                src={artwork.src}
                quality={20}
                width={256}
                height={256}
                alt={artwork.title}
                loading="lazy"
              />
            </Link>
          </div>
        ))}
      </div>
    </>
  );
}
