// components/global/articles-list.vue
<template>
  <main>
    <ContentList path="/articles">
      <div
        v-for="article in content"
        :key="article._path"
        class="card mt-6 p-6 pb-3 transition-colors"
      >
        <div class="">
          <p class="">{{ article.date }}</p>

          <h2>
            <nuxt-link :to="article._path" class="hover:underline">{{
              article.title
            }}</nuxt-link>
          </h2>
        </div>
        <p class="">{{ article.description }}</p>
        <p class="">
          <span class="inline-block" v-for="tag in article.tags">
            <NuxtLink :to="'/articles/tags/' + tag" class="mr-3"
              >#{{ tag }}</NuxtLink
            >
          </span>
        </p>
      </div>
    </ContentList>
  </main>
</template>
<script>
export default {
  props: ["content"],
};
</script>

// src/components/ArticlesList/index.tsx
import { ArticleMeta } from "lib/interface";
import Link from "next/link";

type Props = {
  articles: ArticleMeta[];
};

export default async function Articles({ articles }: Props) {
  return (
    <>
      <article className="">
        {articles.map((article) => (
          <div
            key={article.slug}
            className="border border-[var(--border)] sm:flex w-full  px-8 py-4 rounded-[5px] my-8 "
          >
            <div className="  text-center my-8 sm:my-auto text-[80px] sm:text-[100px] sm:pr-8">
              {article.emoji}
            </div>
            <div>
              <h2 className="mt-0 text-lg xs:text-xl border-l-4 mb-4">
                <Link href={"/articles/" + article.slug}>{article.title}</Link>
              </h2>
              <p className="my-0">
                {article.description}
                <br />
                {article.date}
              </p>

              <div className=" inline-block ">
                {article.tags.map((tag) => (
                  <Link key={tag} href={"/articles/tag/" + tag} className="tag">
                    {"#" + tag}
                  </Link>
                ))}
              </div>
            </div>
          </div>
        ))}
      </article>
    </>
  );
}
