// src/components/Gallery/index.tsx
import { artData } from "lib/data";
import Link from "next/link";
import Image from "next/image";

type Props = {
  className?: string;
  artworks: Array<artData>;
};

export default async function Gallery({ className, artworks }: Props) {
  return (
    <>
      <div className={className + " " + "gallery block"}>
        {artworks.map((artwork) => (
          <div key={artwork.slug} className="w-1/3 inline-block">
            <Link href={"/artworks/" + artwork.slug}>
              <Image
                className="m-0 aspect-square object-cover"
                src={artwork.src}
                quality={20}
                width={256}
                height={256}
                alt={artwork.title}
                loading="lazy"
              />
            </Link>
          </div>
        ))}
      </div>
    </>
  );
}

// components/global/gallery.vue
<template>
  <div
    class="aspect-square bg-gallery over-contain laptop:rounded-b-md"
    style="font-size: 0"
  >
    <div
      v-for="(artwork, i) in artworks"
      :key="i"
      class="w-1/3 inline-block mb-0 hover:opacity-80 transition-opacity"
    >
      <nuxt-link :to="'/artworks/' + artwork.id" :title="artwork.title">
        <nuxt-img
          :alt="artwork.title"
          :src="artwork.image"
          format="webp"
          quality="50"
          width="250"
          height="250"
          loading="lazy"
          class="object-cover aspect-square w-full"
        />
      </nuxt-link>
    </div>
  </div>
</template>
<script>
import artworks from "@/assets/json/artworks.json";
export default {
  data() {
    return {
      artworks: artworks,
    };
  },
};
</script>
