// src/app/artworks/[id]/page.tsx
// kkk
import Link from "next/link";
import artworks_json from "data/db.json";
import NextImage from "components/NextImage";
import { Metadata } from "next";
import Back from "components/Back";
import { ArtworkData } from "lib/interface";

const { artworks } = JSON.parse(JSON.stringify(artworks_json));

export async function generateMetadata({
  params,
}: {
  params: { id: string };
}): Promise<Metadata> {
  const { id } = params;
  const artwork = artworks.find(
    (artwork: ArtworkData) => artwork.id === id
  ) ?? {
    id: "not_found",
    src: "/no-image.png",
    title: "Not Found",
    tag: [],
    href: "",
    description: "",
  };
  return {
    title: `${artwork.title}  | 創作物紹介`,
    description: `${artwork.description}`,
    openGraph: {
      title: `${artwork.title}  | 創作物紹介`,
      description: `${artwork.description}`,
      url: `/artworks/${artwork.id}`,
      type: "article",
      images: {
        url: `${artwork.src}`,
        width: 512,
        height: 512,
      },
    },
    twitter: {
      card: "summary",
      title: `${artwork.title}  | 創作物紹介`,
      description: `${artwork.description}`,
      images: `${artwork.src}`,
      site: "@omemoji_art",
      creator: "@omemoji_art",
    },
  };
}

export default function Artwork({ params }: { params: { id: string } }) {
  const { id } = params;
  const artwork: ArtworkData = artworks.find(
    (artwork: ArtworkData) => artwork.id === id
  ) ?? {
    id: "not_found",
    src: "/no-image.png",
    title: "Not Found",
    tag: [],
    href: "",
    description: "",
  };

  return (
    <>
      <a href={artwork.src}>
        <NextImage
          alt={artwork.title}
          src={artwork.src}
          category="artwork"
          className="content-image"
          priority={true}
        />
      </a>

      <div className="pt-4 pb-8 caption">
        <div className="">
          <h1 className="xs:text-4xl">{artwork.title}</h1>
          <div className="flex justify-center mb-4">
            {artwork.tag.map((tag) => (
              <Link
                href={"/artworks/tag/" + tag}
                key={tag}
                className="tag text-2xl"
              >
                {"#" + tag}
              </Link>
            ))}
          </div>
          <p className=" text-center text-xl mx-auto px-4 ">
            {artwork.description}
          </p>
        </div>
      </div>
      <Back url="/artworks" />
      {/* 
      <Gallery
        artworks={artworks}
        className="border-t border-[color:var(--border)]"
      /> */}
    </>
  );
}

// export const dynamicParams = false;

export function generateStaticParams() {
  return artworks;
}

// pages/Artworks/[id].vue
<template>
  <Head
    ><Title>{{ artwork.title }}</Title>
    <Meta name="description" :content="`${artwork.caption}`" />
    <Meta property="og:site_name" content="創作物紹介" />
    <Meta property="og:type" content="website" />
    <Meta property="og:url" :content="`https://omemoji.com/${$route.path}`" />
    <Meta property="og:title" :content="`${artwork.title}`"/>
    <Meta property="og:description" :content="`${artwork.caption}`"/>
    <Meta property="og:image" :content="`https://omemoji.com/${artwork.image}`"/>
    <Meta name="twitter:card" content="summary" />
    <Meta name="twitter:image" :content="`https://omemoji.com/${artwork.image}`" />
  </Head>

  <div class="card card-shadow m-3 p-3">
    <div class="card bg-white/40 p-3">
      <div class="card">
        <a :href="artwork.image">
          <nuxt-img
            width="760"
            class="content-image"
            :src="artwork.image"
            :alt="artwork.id"
          />
        </a>
      </div>
      <div class="my-3 p-3">
        <h1 class="text-center">{{ artwork.title }}</h1>
      </div>
      <ul class="p-3 pl-6 card">
        <li>
          <h3>Category</h3>
          Artwork
        </li>
        <li>
          <h3>Tools</h3>
          {{ artwork.tool }}
        </li>
        <li>
          <h3>Description</h3>
          <p>{{ artwork.caption }}</p>
        </li>
        <li>
          <h3>Link</h3>
          <a
            :href="artwork.href"
            target="_blank"
            rel="noopener noreferrer"
            class="text-blue-700 break-all"
            >{{ artwork.href }}
          </a>
        </li>
      </ul>
    </div>
  </div>
</template>
<script>
import jsonData from "@/assets/json/artworks.json";

export default {
  data() {
    return {
      // jsonArray: JSON.parse(JSON.stringify(jsonData)),
      artwork: JSON.parse(JSON.stringify(jsonData)).filter((artwork) => {
        return artwork.id === this.$route.params.id;
      })[0],
    };
  },

  head() {
    return {
      meta: [
        {
          hid: "description",
          name: "description",
          content: this.artwork.caption,
        },
        {
          hid: "og:site_name",
          property: "og:site_name",
          content: "創作物紹介",
        },
        { hid: "og:type", property: "og:type", content: "website" },
        {
          hid: "og:url",
          content: "https://omemoji.com/" + `${this.$route.path}`,
        },
        {
          hid: "og:title",
          property: "og:title",
          content: this.artwork.title + " | 創作物紹介",
        },
        {
          hid: "og:description",
          property: "og:description",
          content: this.artwork.caption,
        },
        {
          hid: "og:image",
          property: "og:image",
          content: "https://omemoji.com/omemoji.png",
        },
        { name: "twitter:card", content: "summary" },
      ],
    };
  },
};
</script>
